services:
  bootnode:
    build: .  
    networks:
      eth:
        ipv4_address: 172.10.0.111
    #command: bootnode -nodekey bootnode.key
  auth_node1:
    build: . 
    networks:
      - eth
    #command: geth --nousb --syncmode 'full' --port 30310 --miner.gasprice 0 --miner.gastarget 470000000000 --http --http.vhosts "*" --http.addr 'localhost' --http.port 8545 --http.api admin,eth,miner,net,txpool,personal,web3 --http.corsdomain "*" --mine --allow-insecure-unlock --unlock "0xa273a5c973a6be46ca427d4201b8ab967c04624a" --password /root/.ethereum/keystore/password.txt --bootnodes enode://e6995ea96ec47d206a752fc177653327d5acfa08caf69233836efc164a698ea925ac617d80d53885308282c7b43402978b6cc01f42bb56a4e521a2ae455480f6@127.0.0.1:30301
  auth_node2:
    build: .
    networks:
      - eth
    #command: geth --nousb --syncmode 'full' --port 30310 --miner.gasprice 0 --miner.gastarget 470000000000 --http --http.vhosts "*" --http.addr 'localhost' --http.port 8545 --http.api admin,eth,miner,net,txpool,personal,web3 --http.corsdomain "*" --mine --allow-insecure-unlock --unlock "0x5518d205d80a0cd251011b220b94b3a12e10a261" --password /root/.ethereum/keystore/password.txt --bootnodes enode://e6995ea96ec47d206a752fc177653327d5acfa08caf69233836efc164a698ea925ac617d80d53885308282c7b43402978b6cc01f42bb56a4e521a2ae455480f6@127.0.0.1:30301
  


networks:
  eth:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24