services: 
  ethstat:
    container_name: ethstat
    build:
      context: ./ethstat
    ports:
      - 3000:3000
    environment:
      WS_SECRET: "asdf"
    networks:
      eth:
        ipv4_address: 172.11.0.222
  
  bootnode:
    container_name: bootnode
    build:
      context: ./node
    ports:
      - 30301:30301
    command: bootnode -nodekey /root/bootnode.key -addr 172.11.0.111:30301
    networks:
      eth:
        ipv4_address: 172.11.0.111
  
  node:
    depends_on:
      - bootnode
    build:
      context: ./node
    container_name: node
    ports:
      - 8545:8545
    #command: "tail -f /dev/null"    
    command: geth 
      --syncmode full 
      --bootnodes enode://e6995ea96ec47d206a752fc177653327d5acfa08caf69233836efc164a698ea925ac617d80d53885308282c7b43402978b6cc01f42bb56a4e521a2ae455480f6@172.11.0.111:30301 
      --networkid 7863 
      --http --http.addr 0.0.0.0 --http.corsdomain "*"  --http.api "admin,debug,web3,eth,txpool,personal,clique,miner,net" --netrestrict="172.11.0.0/24"
      --allow-insecure-unlock --unlock "0xa273a5c973a6be46ca427d4201b8ab967c04624a"
      --password /root/.ethereum/keystore/password.txt
      --ethstats node:asdf@172.11.0.222:3000
    networks:
      eth:
        ipv4_address: 172.11.0.66
  
  node-miner-1:
    depends_on:
      - bootnode
    #  - netstats
    build:
      context: ./node
    container_name: miner-1
    ports:
      - 8546:8545
    #command: "tail -f /dev/null"
    command: geth
      --syncmode full 
      --bootnodes enode://e6995ea96ec47d206a752fc177653327d5acfa08caf69233836efc164a698ea925ac617d80d53885308282c7b43402978b6cc01f42bb56a4e521a2ae455480f6@172.11.0.111:30301 
      --networkid 7863 
      --http --http.addr 0.0.0.0 --http.corsdomain "*"  --http.api "admin,debug,web3,eth,txpool,personal,clique,miner,net" 
      --mine --miner.etherbase "0x4ca223bc02517af088e8122a14a0a2e5d1a102f7" --miner.threads 1
      --allow-insecure-unlock --unlock "0x4ca223bc02517af088e8122a14a0a2e5d1a102f7" --password /root/.ethereum/keystore/password.txt -netrestrict="172.11.0.0/24"
      --ethstats node-miner-1:asdf@172.11.0.222:3000
    networks:
      - eth
  
  node-miner-2:
    depends_on:
      - bootnode
    #  - netstats
    build:
      context: ./node
    container_name: miner-2
    ports:
      - 8547:8545
    #command: "tail -f /dev/null"
    command: geth
      --syncmode full
      --bootnodes enode://e6995ea96ec47d206a752fc177653327d5acfa08caf69233836efc164a698ea925ac617d80d53885308282c7b43402978b6cc01f42bb56a4e521a2ae455480f6@172.11.0.111:30301 
      --networkid 7863 
      --http --http.addr 0.0.0.0 --http.corsdomain "*"  --http.api "admin,debug,web3,eth,txpool,personal,clique,miner,net" 
      --mine --miner.etherbase "0x5518d205d80a0cd251011b220b94b3a12e10a261" --miner.threads 1
      --allow-insecure-unlock --unlock "0x5518d205d80a0cd251011b220b94b3a12e10a261" --password /root/.ethereum/keystore/password.txt -netrestrict="172.11.0.0/24"   
      --ethstats node-miner-2:asdf@172.11.0.222:3000
    networks:
      - eth
  
  broker:
    container_name: mqtt-broker
    image: "eclipse-mosquitto:2.0.14"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      eth:
        ipv4_address: 172.11.0.123
  
  publisher:
    depends_on:
      - broker
      - node
    container_name: publisher
    build:
      context: ./publisher
    networks:
      - eth    
  
  subscriber:
    restart: always
    depends_on:
      - server
      - broker
      - node
    container_name: subscriber
    build:
      context: ./subscriber
    networks:
      - eth      
    #command: "tail -f /dev/null"

  server:
    depends_on:
      - broker
      - node
    container_name: server
    build:
      context: ./server
    ports:
      - 5000:5000
    networks:
      eth:
        ipv4_address: 172.11.0.88     
    #command: "tail -f /dev/null"

networks:
  eth:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/24