services:
  bootnode:
    container_name: bootnode
    build:
      context: .
    ports:
      - 30301:30301/udp
    #command: bootnode --nodekeyhex ${BOOTNODE_KEY}
    command: "tail -f /dev/null"
    networks:
      research:
        ipv4_address: 172.11.0.111
  node:
    depends_on:
      - bootnode
    build:
      context: .
    container_name: node
    ports:
      - 8545:8545
    #command: geth
    #  --syncmode full
    #  --bootnodes enode://${BOOTNODE_ID}@172.3.0.111:30301
    #  --networkid ${NETWORK_ID}
    #  --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "eth,web3,net,admin,db"
    #  --ethstats node:${NETSTATS_SECRET}@netstats:3000
    command: "tail -f /dev/null"
    networks:
      - research
  node-miner-1:
    depends_on:
      - bootnode
    #  - netstats
    build:
      context: .
    container_name: node-miner-1
    ports:
      - 8546:8545
    #command: geth
    #  --syncmode full
    #  --bootnodes enode://${BOOTNODE_ID}@172.3.0.111:30301
    #  --networkid ${NETWORK_ID}
    #  --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "eth,web3,net,admin,db,miner"
    #  --mine --miner.etherbase ${ACCOUNT_1}
    #  --unlock ${ACCOUNT_1} --password password.txt
    #  --ethstats node-miner-1:${NETSTATS_SECRET}@netstats:3000
    command: "tail -f /dev/null"
    networks:
      - research
  node-miner-2:
    depends_on:
      - bootnode
    #  - netstats
    build:
      context: .
    container_name: node-miner-2
    ports:
      - 8547:8545
    #command: geth
    #  --syncmode full
    #  --bootnodes enode://${BOOTNODE_ID}@172.3.0.111:30301
    #  --networkid ${NETWORK_ID}
    #  --rpc --rpcaddr 0.0.0.0 --rpccorsdomain "*" --rpcapi "eth,web3,net,admin,db,miner"
    #  --mine --miner.etherbase ${ACCOUNT_2}
    #  --unlock ${ACCOUNT_2} --password password.txt
    #  --ethstats node-miner-2:${NETSTATS_SECRET}@netstats:3000
    command: "tail -f /dev/null"
    networks:
      - research

  
networks:
  research:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/24